teamspace/urls.py
from django.conf.urls import include
from django.conf.urls import url
from teamspace.views import frontend
from teamspace.views import dashboard
from teamspace.views import organization
from teamspace.views import team
from teamspace.views import google

handler404 = 'teamspace.views.errors.handler404'

urlpatterns = [

    # Frontend routes
    url(r'^', include([
        url(r'^$', frontend.home, name='home'),
        url(r'^about/$', frontend.about, name='about'),
        url(r'^login/$', frontend.login, name='login'),
        url(r'^logout/$', frontend.logout, name='logout'),
        url(r'^signup/$', frontend.signup, name='signup'),
    ], namespace='frontend')),

    # Dashboard routes
    url(r'^d/', include([

        # Root dashboard routes
        url(r'^$', dashboard.home, name='home'),

        # Account management routes
        url(r'^u/', include([
            url(r'^edit/$', dashboard.user_edit, name='edit'),
            url(r'^password/$', dashboard.user_password, name='password'),
        ], namespace='user')),

        # Organization access/creation routes
        url(r'^o/', include([
            url(r'^view/$', dashboard.orgs_view, name='view'),
            url(r'^create/$', dashboard.orgs_create, name='create'),
        ], namespace='organization')),

    ], namespace='dashboard')),

    # Organization routes
    url(r'^o/([0-9]+)/', include([

        # Root organization routes
        url(r'^$', organization.home, name='home'),
        url(r'^users/$', organization.users, name='users'),
        url(r'^leave/$', organization.leave, name='leave'),
        url(r'^delete/$', organization.delete, name='delete'),

        # Organization management routes
        url(r'^m/', include([
            url(r'^edit/$', organization.manage_edit, name='edit'),
            url(r'^users/$', organization.manage_users, name='users'),
        ], namespace='manage')),

        # Team access/creation routes
        url(r'^t/', include([
            url(r'^view/$', organization.teams_view, name='view'),
            url(r'^create/$', organization.teams_create, name='create'),
        ], namespace='team')),

    ], namespace='organization')),

    # Team routes
    url(r'^t/([0-9]+)/', include([

        # Root team routes
        url(r'^$', team.home, name='home'),
        url(r'^leave/$', team.leave, name='leave'),
        url(r'^delete/$', team.delete, name='delete'),
        url(r'^events/$', team.events, name='events'),
        url(r'^files/$', team.files, name='files'),
        url(r'^chat/$', team.chat, name='chat'),
        url(r'^users/$', team.users, name='users'),

        # Team management routes
        url(r'^m/', include([
            url(r'^edit/$', team.manage_edit, name='edit'),
            url(r'^users/$', team.manage_users, name='users'),
        ], namespace='manage')),

    ], namespace='team')),

    # Provider routes
    url(r'^providers/', include([

        url(r'^google/$', google.index, name='google'),

    ], namespace='providers')),

]

teamspace/models/event.py
"""
Event Model

This represents details related to a team event.
"""
from django.db import models


class Event(models.Model):
    from teamspace.models import User
    from teamspace.models import Team

    # Database fields
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    parent = models.ForeignKey(Team, on_delete=models.CASCADE)
    title = models.CharField(blank=False, max_length=255)
    description = models.CharField(blank=False, max_length=255)
    start = models.DateField()
    end = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Define instance variables here
    def __init__(self, *args, **kwargs):
        super(Event, self).__init__(*args, **kwargs)
        self.user = None

teamspace/models/file.py
"""
File Model

This represents details related to a team file.
"""
from django.db import models


class File(models.Model):
    from teamspace.models import User
    from teamspace.models import Team

    # Database fields
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    parent = models.ForeignKey(Team, on_delete=models.CASCADE)
    name = models.CharField(blank=False, max_length=255)
    location = models.CharField(blank=False, max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Define instance variables here
    def __init__(self, *args, **kwargs):
        super(File, self).__init__(*args, **kwargs)
        self.user = None

teamspace/forms/event.py
"""
Event Forms

For more information on Forms, see
https://docs.djangoproject.com/en/1.10/topics/forms/

For more information on ModelForms, see
https://docs.djangoproject.com/en/1.10/topics/forms/modelforms/
"""
from django import forms
from teamspace.models import Event


class EventCreateForm(forms.ModelForm):
    """
    The EventCreateForm will create a new message given a team and user.
    """

    # Reference the Message model
    class Meta:
        model = Event
        fields = ['title', 'description', 'start', 'end']
        error_messages = {
            'title': {
                'required': 'Please enter a title.',
            },
            'description': {
                'required': 'Please enter a short description.',
            },
        }

    # Define instance variables here
    def __init__(self, *args, **kwargs):
        self.owner_id = kwargs.pop('owner_id')
        self.parent_id = kwargs.pop('parent_id')
        super(EventCreateForm, self).__init__(*args, **kwargs)

    # Specialized save function
    def save(self, commit=True):
        event = super(EventCreateForm, self).save(commit=False)
        event.owner_id = self.owner_id
        event.parent_id = self.parent_id
        if commit:
            event.save()
        return event

teamspace/forms/team.py
"""
Team Forms

For more information on Forms, see
https://docs.djangoproject.com/en/1.10/topics/forms/

For more information on ModelForms, see
https://docs.djangoproject.com/en/1.10/topics/forms/modelforms/
"""
from django import forms
from teamspace.models import Team
from teamspace.models import TeamMembership

FIELDS = ['name', 'description']
ERRORS = {
    'name': {
        'required': 'Please enter your team name.',
        'unique': 'This team name is taken.',
    },
    'description': {
        'required': 'Please enter a team description.',
    },
}


class TeamCreateForm(forms.ModelForm):
    """
    The TeamCreateForm will create a new team given the required fields and
    create a TeamMembership record when the form is saved and committed.
    """

    # Reference the Team model
    class Meta:
        model = Team
        fields = FIELDS
        error_messages = ERRORS

    # Define instance variables here
    def __init__(self, *args, **kwargs):
        self.owner_id = kwargs.pop('owner_id')
        self.parent_id = kwargs.pop('parent_id')
        super(TeamCreateForm, self).__init__(*args, **kwargs)

    # Specialized save function
    def save(self, commit=True):
        team = super(TeamCreateForm, self).save(commit=False)
        team.owner_id = self.owner_id
        team.parent_id = self.parent_id
        if commit:
            team.save()
            TeamMembership.objects.create(team_id=team.id, user_id=team.owner_id)
        return team


class TeamEditForm(forms.ModelForm):
    """
    The TeamEditForm will update an existing team given an instance
    of the Team and post data if it exists. The Team will be saved
    when the form is saved.
    """

    # Reference the Team model
    class Meta:
        model = Team
        fields = FIELDS
        error_messages = ERRORS

teamspace/views/team.py
"""
Team Controller

For more information on controllers (views), see
https://docs.djangoproject.com/en/1.10/#the-view-layer

For the full list of requests and their responses, see
https://docs.djangoproject.com/en/1.10/ref/request-response/
"""
import os
from django.views.static import serve
from django.http import Http404
from django.contrib import messages
from django.shortcuts import render
from django.shortcuts import redirect
from teamspace.utils import get_users
from teamspace.utils import get_files
from teamspace.utils import get_events
from teamspace.utils import get_messages
from teamspace.utils import format_errors
from teamspace.utils import format_description
from teamspace.models import File
from teamspace.models import Team
from teamspace.models import TeamMembership
from teamspace.models import Organization
from teamspace.forms.user import AddMember
from teamspace.forms.team import TeamEditForm
from teamspace.forms.event import EventCreateForm
from teamspace.forms.message import MessageCreateForm
from teamspace.views.decorators import require_team_owner
from teamspace.views.decorators import require_team_member
from teamspace.views.decorators import require_authenticated


@require_authenticated
@require_team_member
def leave(request, id):
    """
    Deletes the membership record of the queried team if the user is a member.

    :param request:
    :param id: Team ID
    :return: redirect
    """

    # Fetch the corresponding team
    try:
        team = Team.objects.get(pk=id)
    except Team.DoesNotExist:
        raise Http404()

    # Fetch the parent organization
    try:
        organization = Organization.objects.defer('description', 'address', 'country', 'state').get(pk=team.parent_id)
    except Organization.DoesNotExist:
        raise Http404()

    # Fetch the corresponding team membership
    try:
        membership = TeamMembership.objects.get(user_id=request.user.id, team_id=team.id)
    except TeamMembership.DoesNotExist:
        raise Http404()

    # Delete the membership and decrement the member count
    if membership:
        membership.delete()
        team.members -= 1
        team.save()
        messages.info(request, 'You have left the team.')

    # Redirect the user back to the team view
    return redirect('organization:team:view', organization.id)


@require_authenticated
@require_team_owner
def delete(request, id):
    """
    Deletes the queried team if the user is the owner.

    :param request:
    :param id: Team ID
    :return: redirect
    """

    # Fetch the corresponding team
    try:
        team = Team.objects.get(pk=id)
    except Team.DoesNotExist:
        raise Http404()

    # Fetch the parent organization
    try:
        organization = Organization.objects.defer('description', 'address', 'country', 'state').get(pk=team.parent_id)
    except Organization.DoesNotExist:
        raise Http404()

    # Make sure the user is the owner
    if team.owner_id == request.user.id:
        team.delete()
        messages.info(request, 'The team has been deleted.')

    # Redirect the user back to the team view
    return redirect('organization:team:view', organization.id)


@require_authenticated
@require_team_member
def home(request, id):
    """
    Returns a view with the queried team and a parsed markdown description.

    :param request:
    :param id: Team ID
    :return: render
    """

    # Fetch the corresponding team
    try:
        team = Team.objects.get(pk=id)
    except Team.DoesNotExist:
        raise Http404()

    # Parse the description
    team.markdown = format_description(team.description)

    # Fetch the parent organization
    try:
        organization = Organization.objects.defer('description', 'address', 'country', 'state').get(pk=team.parent_id)
    except Organization.DoesNotExist:
        raise Http404()

    # Give the template a title
    title = team.name + ': About'

    # Render the template with the queried data set
    return render(request, 'backend/team/home.html', {
        'title': title, 'team': team, 'organization': organization,
    })


@require_authenticated
@require_team_member
def events(request, id):
    """
    Returns a view with the queried team and a list of events.

    :param request:
    :param id: Team ID
    :return: render
    """

    # Fetch the corresponding team
    try:
        team = Team.objects.defer('description').get(pk=id)
    except Team.DoesNotExist:
        raise Http404()

    # Fetch the parent organization
    try:
        organization = Organization.objects.defer('description', 'address', 'country', 'state').get(pk=team.parent_id)
    except Organization.DoesNotExist:
        raise Http404()

    # Give the template a title
    title = team.name + ': Events'

    # Initialize the form
    form = None

    # Handle post methods
    if request.method == 'POST':

        # Process the post data in the form
        form = EventCreateForm(request.POST, owner_id=request.user.id, parent_id=team.id)

        # Check if the form is valid and create the message
        if form.is_valid():
            form.save()
            form = None

        # Post an error message
        else:
            messages.error(request, format_errors(form.errors))

    # Fetch the event list
    events = get_events(team.id)

    # Post a message if empty
    if not events:
        messages.info(request, 'There are no events to display.')

    # Render the template with the queried data set
    return render(request, 'backend/team/events.html', {
        'title': title, 'team': team, 'organization': organization,
        'form': form, 'events': events,
    })


@require_authenticated
@require_team_member
def files(request, id):
    """
    Returns a view with a file manager window in the queried team.

    :param request:
    :param id: Team ID
    :return: render
    """
    from teamspace import settings

    if request.method == 'GET':
        if request.GET.get('file_id'):
            try:
                # This does not scale well, but it'll work for a presentation
                fid = int(request.GET.get('file_id'))
                file = File.objects.get(pk=fid)
                if file.parent_id == int(id):
                    return serve(request, os.path.basename(file.location), os.path.dirname(file.location))
                else:
                    messages.error(request, 'This file could not be found.')
            except ValueError:
                messages.error(request, 'Invalid file ID.')

    # Fetch the corresponding team
    try:
        team = Team.objects.defer('description').get(pk=id)
    except Team.DoesNotExist:
        raise Http404()

    # Fetch the parent organization
    try:
        organization = Organization.objects.defer('description', 'address', 'country', 'state').get(pk=team.parent_id)
    except Organization.DoesNotExist:
        raise Http404()

    # Give the template a title
    title = team.name + ': Files'

    # Upload the requested file
    if request.method == 'POST':
        from teamspace.views.google import authorize
        google_request = {'team_id': team.id, 'file_id': request.POST.get('file_id')}
        return redirect(authorize(request, google_request))

    # Fetch the file list
    files = get_files(team.id)

    # Post a message if empty
    if not files:
        messages.info(request, 'There are no files to display. Share some!')

    # Render the template with the queried data set
    return render(request, 'backend/team/files.html', {
        'title': title, 'team': team,
        'organization': organization, 'files': files,
        'app_id': settings.PROVIDERS.get('GOOGLE').get('ID'),
        'api_key': settings.PROVIDERS.get('GOOGLE').get('APIKEY'),
        'client_id': settings.PROVIDERS.get('GOOGLE').get('CLIENT'),
    })


@require_authenticated
@require_team_member
def chat(request, id):
    """
    Returns a view with a chat window for the queried team.

    :param request:
    :param id: Team ID
    :return: render
    """

    # Fetch the corresponding team
    try:
        team = Team.objects.defer('description').get(pk=id)
    except Team.DoesNotExist:
        raise Http404()

    # Fetch the parent organization
    try:
        organization = Organization.objects.defer('description', 'address', 'country', 'state').get(pk=team.parent_id)
    except Organization.DoesNotExist:
        raise Http404()

    # Give the template a title
    title = team.name + ': Chat'

    # Initialize the form
    form = None

    # Handle post methods
    if request.method == 'POST':

        # Process the post data in the form
        form = MessageCreateForm(request.POST, owner_id=request.user.id, parent_id=team.id)

        # Check if the form is valid and create the message
        if form.is_valid():
            form.save()
            form = None

        # Post an error message
        else:
            messages.error(request, 'Your message could not be posted.')

    # Fetch the message list
    team_messages = get_messages(team.id)

    # Post a message if empty
    if not team_messages:
        messages.info(request, 'There are no messages to display.')

    # Render the template with the queried data set
    return render(request, 'backend/team/chat.html', {
        'title': title, 'team': team, 'organization': organization,
        'form': form, 'team_messages': team_messages,
    })


@require_authenticated
@require_team_member
def users(request, id):
    """
    Returns a view with a list of members in the queried team.

    :param request:
    :param id: Team ID
    :return: render
    """

    # Fetch the corresponding team
    try:
        team = Team.objects.defer('description').get(pk=id)
    except Team.DoesNotExist:
        raise Http404()

    # Fetch a list of team members
    users = get_users(id, 'team')

    # Fetch the parent organization
    try:

templates/backend/team/chat.html
{% extends 'backend/layouts/base.html' %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        {{ team.name }}
        <div class="sub header">
            Chat
        </div>
    </h2>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <!-- Message form -->
    <form class="ui form" style="width: 100%;" method="POST" action="{% url 'team:chat' team.id %}">
        <h4 class="ui dividing header">Post a Message</h4>
        <table style="width: 100%;">
            <tr>
                <td style="width: 90%; padding: 5px;">
                    <div class="field">
                        <input type="text" name="message" placeholder="Say something..." maxlength="255" required>
                    </div>
                </td>
                <td style="width: 10%; padding: 5px;">
                    {% csrf_token %}
                    <button class="ui green button" type="submit">Send</button>
                </td>
            </tr>
        </table>
    </form>
    {% if team_messages %}
        <!-- Chat log -->
        <h4 class="ui dividing header" style="width: 100%;">Chat Log</h4>
        {% for team_message in team_messages %}
            <div class="ui small message" style="width: 100%;">
                <div class="header" style="font-size: 10pt;">{{ team_message.user.first_name }} {{ team_message.user.last_name }}, {{ team_message.created|timesince }} ago</div>
                <p>{{ team_message.message }}</p>
            </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

templates/backend/team/events.html
{% extends 'backend/layouts/base.html' %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        {{ team.name }}
        <div class="sub header">
            Events
        </div>
    </h2>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <!-- Message form -->
    <form class="ui form" style="width: 100%;" method="POST" action="{% url 'team:events' team.id %}">
        <h4 class="ui dividing header">Create an Event</h4>
        <div class="field">
            <label>Name</label>
            <input type="text" name="title" placeholder="Title" maxlength="255" value="{{ form.data.title }}" required>
        </div>
        <div class="two fields">
            <div class="field">
                <label>Start Date</label>
                <input type="date" name="start" value="{{ form.data.start }}" required>
            </div>
            <div class="field">
                <label>End Date</label>
                <input type="date" name="end" value="{{ form.data.end }}" required>
            </div>
        </div>
        <div class="field">
            <label>Description</label>
            <textarea name="description" placeholder="Description" rows="2" maxlength="255" required>{{ form.data.description }}</textarea>
        </div>
        {% csrf_token %}
        <button class="ui green button" type="submit">Create</button>
    </form>
    {% if events %}
        <!-- Chat log -->
        <h4 class="ui dividing header" style="width: 100%;">Event List</h4>
        {% for event in events %}
            <div class="ui small message" style="width: 100%;">
                <div class="header" style="font-size: 10pt;">{{ event.title }}: {{ event.start|date:"M d, Y" }} - {{ event.end|date:"M d, Y" }}</div>
                <p>{{ event.description }} - <em>{{ event.user.first_name }} {{ event.user.last_name }}</em></p>
            </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

templates/backend/team/files.html
{% extends 'backend/layouts/base.html' %}
{% load static %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        {{ team.name }}
        <div class="sub header">
            Files
        </div>
    </h2>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <!-- Hidden upload form -->
    <form id="hidden" method="POST" action="{% url 'team:files' team.id %}">
        <input type="hidden" name="file_id">
        {% csrf_token %}
    </form>
    <button class="ui google plus button" style="width: 100%;" onclick="loadPicker()">
        <i class="google icon"></i>
        Share a file from Google Drive
    </button>
    <!-- List of files -->
    {% if files %}
        <h4 class="ui dividing header" style="width: 100%;">Shared Files</h4>
        {% for file in files %}
            <div class="ui small message" style="width: 100%;">
                <table style="width: 100%;">
                    <tr>
                        <td style="width: 100%;">
                            <div class="header" style="font-size: 10pt;">{{ file.name }}</div>
                            Uploaded by {{ file.user.first_name }} {{ file.user.last_name }}, {{ file.created|timesince }} ago
                        </td>
                        <td>
                            <a href="?file_id={{ file.id }}"><i class="download icon" style="font-size: 20pt; padding-top: 5px;"></i></a>
                        </td>
                    </tr>
                </table>
            </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/backend.picker.js' %}"></script>
<script type="text/javascript" src="https://apis.google.com/js/api.js">' + '</script>
<script type="text/javascript">initPicker('{{ api_key }}', '{{ client_id }}', '{{ app_id }}');</script>
{% endblock %}

templates/backend/team/home.html
{% extends 'backend/layouts/base.html' %}
{% load static %}

{% block styles %}
<!-- Markdown specific styles -->
<link rel="stylesheet" href="{% static 'css/backend.md.css' %}">
{% endblock %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        {{ team.name }}
        <div class="sub header">
            Home
        </div>
    </h2>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div>
    {{ team.markdown|safe }}
</div>
{% endblock %}

templates/backend/team/manage_edit.html
{% extends 'backend/layouts/base.html' %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        {{ team.name }}
        <div class="sub header">
            Manage
        </div>
    </h2>
    <div class="right menu">
        <a class="ui active item">
            Edit
        </a>
        <a class="ui item" href="{% url 'team:manage:users' team.id %}">
            Users
        </a>
    </div>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    {% include 'backend/partials/team_form.html' %}
</div>
{% endblock %}

templates/backend/team/manage_users.html
{% extends 'backend/layouts/base.html' %}
{% load static %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        {{ team.name }}
        <div class="sub header">
            Manage
        </div>
    </h2>
    <div class="right menu">
        <a class="ui item" href="{% url 'team:manage:edit' team.id %}">
            Edit
        </a>
        <a class="ui active item">
            Users
        </a>
    </div>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <!-- Invitation form -->
    <form class="ui form" style="width: 100%;" method="POST" action="{% url 'team:manage:users' team.id %}">
        <h4 class="ui dividing header">Invite Users</h4>
        <table style="width: 100%;">
            <tr>
                <td style="width: 90%; padding: 5px;">
                    <div class="field">
                        <input type="email" name="email" placeholder="Email address" value="{{ form.data.email }}" required>
                    </div>
                </td>
                <td style="width: 10%; padding: 5px;">
                    {% csrf_token %}
                    <button class="ui green button" type="submit">Invite</button>
                </td>
            </tr>
        </table>
    </form>
    <!-- User table -->
    {% if team.members > 1 %}
        <table class="ui very basic striped celled table">
            <thead>
                <tr>
                    <th style="width: 70%;">User</th>
                    <th style="width: 20%;">Member Since</th>
                    <th style="width: 10%;">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    {% if user.id != request.user.id %}
                    <tr>
                        <td>{{ user.first_name }} {{ user.last_name }}</td>
                        <td>{{ user.member_date|date:"M d, Y" }}</td>
                        <td><a class="ui red button" onclick="remove('{{ user.id }}')">Remove</a></td>
                    </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
    <!-- Hidden remove form -->
    <form class="ui form" id="hidden" style="width: 100%;" method="POST" action="{% url 'team:manage:users' team.id %}">
        <input type="hidden" name="id">
        {% csrf_token %}
    </form>
</div>
{% endblock %}

{% block scripts %}
<!-- SCRIPT: Hidden form controller -->
<script type="text/javascript" src="{% static 'js/backend.manage.js' %}"></script>
{% endblock %}

templates/backend/team/users.html
{% extends 'backend/layouts/base.html' %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        {{ team.name }}
        <div class="sub header">
            Users
        </div>
    </h2>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <table class="ui very basic striped celled table">
        <thead>
            <tr>
                <th style="width: 80%;">User</th>
                <th style="width: 20%;">Member Since</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.first_name }} {{ user.last_name }}</td>
                <td>{{ user.member_date|date:"M d, Y" }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}