teamspace/urls.py
from django.conf.urls import include
from django.conf.urls import url
from teamspace.views import frontend
from teamspace.views import dashboard
from teamspace.views import organization
from teamspace.views import team
from teamspace.views import google

handler404 = 'teamspace.views.errors.handler404'

urlpatterns = [

    # Frontend routes
    url(r'^', include([
        url(r'^$', frontend.home, name='home'),
        url(r'^about/$', frontend.about, name='about'),
        url(r'^login/$', frontend.login, name='login'),
        url(r'^logout/$', frontend.logout, name='logout'),
        url(r'^signup/$', frontend.signup, name='signup'),
    ], namespace='frontend')),

    # Dashboard routes
    url(r'^d/', include([

        # Root dashboard routes
        url(r'^$', dashboard.home, name='home'),

        # Account management routes
        url(r'^u/', include([
            url(r'^edit/$', dashboard.user_edit, name='edit'),
            url(r'^password/$', dashboard.user_password, name='password'),
        ], namespace='user')),

        # Organization access/creation routes
        url(r'^o/', include([
            url(r'^view/$', dashboard.orgs_view, name='view'),
            url(r'^create/$', dashboard.orgs_create, name='create'),
        ], namespace='organization')),

    ], namespace='dashboard')),

    # Organization routes
    url(r'^o/([0-9]+)/', include([

        # Root organization routes
        url(r'^$', organization.home, name='home'),
        url(r'^users/$', organization.users, name='users'),
        url(r'^leave/$', organization.leave, name='leave'),
        url(r'^delete/$', organization.delete, name='delete'),

        # Organization management routes
        url(r'^m/', include([
            url(r'^edit/$', organization.manage_edit, name='edit'),
            url(r'^users/$', organization.manage_users, name='users'),
        ], namespace='manage')),

        # Team access/creation routes
        url(r'^t/', include([
            url(r'^view/$', organization.teams_view, name='view'),
            url(r'^create/$', organization.teams_create, name='create'),
        ], namespace='team')),

    ], namespace='organization')),

    # Team routes
    url(r'^t/([0-9]+)/', include([

        # Root team routes
        url(r'^$', team.home, name='home'),
        url(r'^leave/$', team.leave, name='leave'),
        url(r'^delete/$', team.delete, name='delete'),
        url(r'^events/$', team.events, name='events'),
        url(r'^files/$', team.files, name='files'),
        url(r'^chat/$', team.chat, name='chat'),
        url(r'^users/$', team.users, name='users'),

        # Team management routes
        url(r'^m/', include([
            url(r'^edit/$', team.manage_edit, name='edit'),
            url(r'^users/$', team.manage_users, name='users'),
        ], namespace='manage')),

    ], namespace='team')),

    # Provider routes
    url(r'^providers/', include([

        url(r'^google/$', google.index, name='google'),

    ], namespace='providers')),

]

teamspace/views/dashboard.py
"""
Dashboard Controller

For more information on controllers (views), see
https://docs.djangoproject.com/en/1.10/#the-view-layer

For the full list of requests and their responses, see
https://docs.djangoproject.com/en/1.10/ref/request-response/
"""
from django.contrib import messages
from django.shortcuts import render
from django.shortcuts import redirect
from teamspace.utils import format_errors
from teamspace.models import Organization
from teamspace.models import OrganizationMembership
from teamspace.forms.organization import OrganizationCreateForm
from teamspace.views.decorators import require_authenticated


@require_authenticated
def home(request):
    """
    Returns a view that acts as a starting point for the user.

    :param request:
    :return: render, redirect
    """

    # Give the template a title
    title = 'Dashboard: Home'

    # Render the template with the queried data set
    return render(request, 'backend/dashboard/home.html', {'title': title})


@require_authenticated
def user_edit(request):
    """
    Returns a view with a form for the user to edit their account.

    :param request:
    :return: render, redirect
    """

    # Give the template a title
    title = 'Dashboard: Edit Account'

    # Render the template with the queried data set
    return render(request, 'backend/dashboard/user_edit.html', {'title': title})


@require_authenticated
def user_password(request):
    """
    Returns a view with a form for the user to change their password.

    :param request:
    :return: render, redirect
    """

    # Give the template a title
    title = 'Dashboard: Change Password'

    # Render the template with the queried data set
    return render(request, 'backend/dashboard/user_password.html', {'title': title})


@require_authenticated
def orgs_view(request):
    """
    Returns a view containing a list of organizations the user is a member of.

    :param request:
    :return: render, redirect
    """

    # Get the list of organizations where the user is a member
    memberships = OrganizationMembership.objects.filter(user_id=request.user.id)
    organizations = []

    # Fetch each organization given a membership
    for membership in memberships:
        organizations.append(Organization.objects.defer('description', 'address', 'country', 'state').get(pk=membership.organization_id))

    # Fetch a list of active teams for each organization
    for organization in organizations:
        organization.set_active_teams(request.user.id)

    # Flash a message if the list of teams is empty
    if not organizations:
        messages.info(request, 'You\'re not a member of any organization yet. Go create one!')

    # Give the template a title
    title = 'Dashboard: View Organizations'

    # Render the template with the queried data set
    return render(request, 'backend/dashboard/organizations_view.html', {
        'title': title, 'organizations': organizations,
    })


@require_authenticated
def orgs_create(request):
    """
    Returns a view where users can create an organization.

    :param request:
    :return: render, redirect
    """

    # Give the template a title
    title = 'Dashboard: Create Organization'

    # Handle a POST method
    if request.method == 'POST':

        # Process the post data in the form
        form = OrganizationCreateForm(request.POST, owner_id=request.user.id)

        # Check if the form is valid
        if form.is_valid():

            # Create the organization
            organization = form.save()

            # Post a success message
            messages.success(request, 'Organization successfully created.')

            # Redirect to the newly created team
            return redirect('organization:home', organization.id)

        else:

            # Post an error message
            messages.error(request, format_errors(form.errors))

            # Return with the errors otherwise
            return render(request, 'backend/dashboard/organizations_create.html', {
                'title': title, 'form': form,
            })

    # Render the creation template
    return render(request, 'backend/dashboard/organizations_create.html', {'title': title})

teamspace/views/organization.py
"""
Organization Controller

For more information on controllers (views), see
https://docs.djangoproject.com/en/1.10/#the-view-layer

For the full list of requests and their responses, see
https://docs.djangoproject.com/en/1.10/ref/request-response/
"""
from django.http import Http404
from django.contrib import messages
from django.shortcuts import render
from django.shortcuts import redirect
from teamspace.utils import get_users
from teamspace.utils import format_errors
from teamspace.utils import format_description
from teamspace.models import Team
from teamspace.models import Organization
from teamspace.models import OrganizationMembership
from teamspace.forms.user import AddMember
from teamspace.forms.team import TeamCreateForm
from teamspace.forms.organization import OrganizationEditForm
from teamspace.views.decorators import require_org_owner
from teamspace.views.decorators import require_org_member
from teamspace.views.decorators import require_authenticated


@require_authenticated
@require_org_member
def leave(request, id):
    """
    Deletes the membership record of the queried organization if the user is a member.

    :param request:
    :param id: Organization ID
    :return: redirect
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()

    # Fetch the corresponding organization membership
    try:
        membership = OrganizationMembership.objects.get(user_id=request.user.id, organization_id=organization.id)
    except OrganizationMembership.DoesNotExist:
        raise Http404()

    # Delete the membership and decrement the member count
    if membership:
        membership.delete()
        organization.members -= 1
        organization.save()
        messages.info(request, 'You have left the organization.')

    # Redirect the user back to the organization view
    return redirect('dashboard:organization:view')


@require_authenticated
@require_org_owner
def delete(request, id):
    """
    Deletes the queried organization if the user is the owner.

    :param request:
    :param id: Organization ID
    :return: redirect
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()

    # Make sure the user is the owner
    if organization.owner_id == request.user.id:
        organization.delete()
        messages.info(request, 'The organization has been deleted.')

    # Redirect the user back to the organization view
    return redirect('dashboard:organization:view')


@require_authenticated
@require_org_member
def home(request, id):
    """
    Returns a view with the queried organization and a parsed markdown description.

    :param request:
    :param id: Organization ID
    :return: render
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()

    # Parse the description
    organization.markdown = format_description(organization.description)

    # Give the template a title
    title = organization.name + ': Home'

    # Render the template with the queried data set
    return render(request, 'backend/organization/home.html', {
        'title': title, 'organization': organization,
    })


@require_authenticated
@require_org_member
def users(request, id):
    """
    Returns a view containing a list of members in the queried organization.

    :param request:
    :param id: Organization ID
    :return: render
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.defer('description', 'address', 'country', 'state').get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()

    # Get a list of organization members (as users)
    users = get_users(id, 'organization')

    # Give the template a title
    title = organization.name + ': Users'

    # Render the template with the queried data set
    return render(request, 'backend/organization/users.html', {
        'title': title, 'users': users, 'organization': organization,
    })


@require_authenticated
@require_org_member
def teams_view(request, id):
    """
    Returns a view containing a list of teams in the queried organization.

    :param request:
    :param id: Organization ID
    :return: render
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.defer('description', 'address', 'country', 'state').get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()

    # TODO: If the user is the organization owner, show all the teams.
    # TODO: If they are not the owner, then only show teams where they are a member.
    # Fetch the corresponding list of teams
    teams = Team.objects.defer('description').filter(parent_id=id)

    # Flash a message if the list of teams is empty
    if not teams:
        messages.info(request, 'Your organization does not have any teams. Go create one!')

    # Give the template a title
    title = organization.name + ': View Teams'

    # Render the template with the queried data set
    return render(request, 'backend/organization/teams_view.html', {
        'title': title, 'teams': teams, 'organization': organization,
    })


@require_authenticated
@require_org_member
def teams_create(request, id):
    """
    Returns a view where users can create a team within the queried organization.

    :param request:
    :param id: Organization ID
    :return: render, redirect
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.defer('description', 'address', 'country', 'state').get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()

    # Give the template a title
    title = organization.name + ': Create Team'

    # Handle a POST method
    if request.method == 'POST':

        # Process the post data in the form
        form = TeamCreateForm(request.POST, parent_id=id, owner_id=request.user.id)

        # Check if the form is valid
        if form.is_valid():

            # Create the team
            team = form.save()

            # Post a success message
            messages.success(request, 'Team successfully created.')

            # Redirect to the newly created team
            return redirect('team:home', team.id)

        else:

            # Post an error message
            messages.error(request, format_errors(form.errors))

            # Return with the errors otherwise
            return render(request, 'backend/organization/teams_create.html', {
                'title': title, 'form': form, 'organization': organization,
            })

    # Render the template with the queried data set
    return render(request, 'backend/organization/teams_create.html', {
        'title': title, 'organization': organization,
    })


@require_authenticated
@require_org_owner
def manage_edit(request, id):
    """
    Returns a view where an owner can edit their organization.

    :param request:
    :param id: Organization ID
    :return: render
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()

    # Give the template a title
    title = organization.name + ': Edit'

    # Handle a POST method
    if request.method == 'POST':

        # Update the form with the post data
        form = OrganizationEditForm(request.POST, instance=organization)

        # Check if the form is valid
        if form.is_valid():

            # Update and save the organization
            form.save()

            # Post a success message
            messages.success(request, 'Settings successfully saved.')

        else:

            # Post an error message
            messages.error(request, format_errors(form.errors))

    else:

        # Give the default form
        form = OrganizationEditForm(instance=organization)

    # Render the template with the queried data set
    return render(request, 'backend/organization/manage_edit.html', {
        'title': title, 'form': form, 'organization': organization,
    })


@require_authenticated
@require_org_owner
def manage_users(request, id):
    """
    Returns a view with a list of users and a form to add users.

    :param request:
    :param id: Organization ID
    :return: render
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.defer('description', 'address', 'country', 'state').get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()
    form = None

    # Handle a POST method
    if request.method == 'POST':

        # Handle invitations by creating a membership record
        if 'email' in request.POST:

            # Process the email address
            form = AddMember(request.POST, id=id, organization=True)

            # Check if the form is valid
            if form.is_valid():

                # Create the membership record
                form.add_member()
                organization.members += 1
                organization.save()

                # Post a success message
                messages.success(request, 'User successfully added.')

            else:

                # Post an error message
                messages.error(request, format_errors(form.errors))

        # Handle removals by deleting the membership record
        if 'id' in request.POST:

            # ID is non-user controlled, so assume it's safe
            remove_user_id = int(request.POST.get('id'))

            # Find and delete the membership record
            try:
                OrganizationMembership.objects.get(user_id=remove_user_id, organization_id=id).delete()
            except OrganizationMembership.DoesNotExist:

templates/backend/dashboard/home.html
{% extends 'backend/layouts/base.html' %}
{% load static %}

{% block styles %}
<!-- Add some spacing between the buttons -->
<link rel="stylesheet" href="{% static 'css/backend.grid.css' %}">
{% endblock %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        Dashboard
        <div class="sub header">
            Home
        </div>
    </h2>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <table style="width: 100%;">
        <tr>
            <td class="dashboard">
                <a class="fluid ui green button" style="padding: 50px; border-radius: 10px;" href="{% url 'dashboard:organization:view' %}">
                    <p style="font-size: 18pt;">Organizations</p>
                    <p style="font-size: 12pt;">Select an organization to get started.</p>
                </a>
            </td>
            <td class="dashboard">
                <a class="fluid ui blue button" style="padding: 50px; border-radius: 10px;" href="{% url 'dashboard:user:edit' %}">
                    <p style="font-size: 18pt;">Account</p>
                    <p style="font-size: 12pt;">View, edit, or delete your account.</p>
                </a>
            </td>
        </tr>
    </table>
</div>
{% endblock %}

templates/backend/dashboard/organizations_create.html
{% extends 'backend/layouts/base.html' %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        Organizations
        <div class="sub header">
            Create
        </div>
    </h2>
    <div class="right menu">
        <a class="ui item" href="{% url 'dashboard:organization:view' %}">
            Select
        </a>
        <a class="ui active item">
            Create
        </a>
    </div>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    {% include 'backend/partials/organization_form.html' %}
</div>
{% endblock %}

{% block scripts %}
<!-- SCRIPT: Organization form -->
<script type="text/javascript">
    var country = '{{ form.data.country }}';
    var state = '{{ form.data.state }}';
    $('[name=country]').dropdown('set selected', country);
    $('[name=state]').dropdown('set selected', state);
</script>
{% endblock %}

templates/backend/dashboard/organizations_view.html
{% extends 'backend/layouts/base.html' %}
{% load static %}

{% block body %}
<!-- Delete-Leave modal -->
<div class="ui small modal" id="verify">
    <div class="header" id="verify-title"></div>
    <div class="content">
        <div align="center" id="verify-description"></div>
    </div>
    <div class="actions">
        <a class="ui cancel button" type="reset">Cancel</a>
        <a class="ui red submit button" id="verify-link" type="submit"></a>
    </div>
</div>

<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        Organizations
        <div class="sub header">
            Select
        </div>
    </h2>
    <div class="right menu">
        <a class="ui active item">
            Select
        </a>
        <a class="ui item" href="{% url 'dashboard:organization:create' %}">
            Create
        </a>
    </div>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    {% if organizations %}
    <table class="ui very basic striped celled table">
        <thead>
            <tr>
                <th style="width: 30%;">Organization</th>
                <th style="width: 40%;">Active Teams</th>
                <th style="width: 20%;">Members</th>
                <th style="width: 10%;">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for organization in organizations %}
            <tr>
                <td>{{ organization.name }}</td>
                <td>
                    {% if organization.active_teams %}
                        {% for active_team in organization.active_teams %}
                            {% if forloop.last %}
                                {{ active_team.name }}.
                            {% else %}
                                {{ active_team.name }},
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        (No active teams)
                    {% endif %}
                </td>
                <td>{{ organization.members }}</td>
                <td>
                    {% if organization.owner_id == request.user.id %}
                     <div class="ui blue buttons">
                         <a class="ui button" href="{% url 'organization:team:view' organization.id %}">Select</a>
                         <div class="ui floating dropdown icon button">
                             <i class="dropdown icon"></i>
                             <div class="menu">
                                 <a class="item" href="{% url 'organization:manage:edit' organization.id %}"><i class="edit icon"></i> Manage</a>
                                 <a class="item" onclick="verify('{% url 'organization:delete' organization.id %}', 'delete', 'organization')"><i class="delete icon"></i> Delete</a>
                             </div>
                         </div>
                     </div>
                     {% else %}
                     <div class="ui green buttons">
                        <a class="ui button" href="{% url 'organization:team:view' organization.id %}">Select</a>
                        <div class="ui floating dropdown icon button">
                            <i class="dropdown icon"></i>
                            <div class="menu">
                                <a class="item" onclick="verify('{% url 'organization:leave' organization.id %}', 'leave', 'organization')"><i class="sign out icon"></i> Leave</a>
                            </div>
                        </div>
                     </div>
                     {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
<!-- SCRIPT: Delete-Leave modal -->
<script type="text/javascript" src="{% static 'js/backend.manage.js' %}"></script>
{% endblock %}

templates/backend/dashboard/user_edit.html
{% extends 'backend/layouts/base.html' %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        Account
        <div class="sub header">
            Settings
        </div>
    </h2>
    <div class="right menu">
        <a class="ui active item">
            Edit Account
        </a>
        <a class="ui item" href="{% url 'dashboard:user:password' %}">
            Change Password
        </a>
    </div>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <!-- Edit account information -->
    <form class="ui form" style="width: 100%;" method="POST" action="">
        <h4 class="ui dividing header">Account Information</h4>
        <div class="two fields">
            <div class="field">
                <label>First name</label>
                <input type="text" name="first_name" placeholder="First name" maxlength="30" required>
            </div>
            <div class="field">
                <label>Last name</label>
                <input type="text" name="last_name" placeholder="Last name" maxlength="30" required>
            </div>
        </div>
        <div class="two fields">
            <div class="field">
                <label>Username</label>
                <input type="text" name="username" placeholder="Username" maxlength="20" required>
            </div>
            <div class="field">
                <label>Email address</label>
                <input type="email" name="email" placeholder="Email address" required>
            </div>
        </div>
        <div class="field">
            <label>Confirm password</label>
            <div class="ui left icon input">
                <i class="lock icon"></i>
                <input type="password" name="password_two" placeholder="Confirm password" required>
            </div>
        </div>
        <br>
        {% csrf_token %}
        <button class="ui green button" type="submit">Save</button>
    </form>
</div>
{% endblock %}

templates/backend/dashboard/user_password.html
{% extends 'backend/layouts/base.html' %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        Account
        <div class="sub header">
            Settings
        </div>
    </h2>
    <div class="right menu">
        <a class="ui item" href="{% url 'dashboard:user:edit' %}">
            Edit Account
        </a>
        <a class="ui active item">
            Change Password
        </a>
    </div>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <!-- Change password -->
    <form class="ui form" style="width: 100%;" method="POST" action="">
        <h4 class="ui dividing header">Change Password</h4>
        <div class="field">
            <label>Old password</label>
            <div class="ui left icon input">
                <i class="lock icon"></i>
                <input type="password" name="password_old" placeholder="Old password" required>
            </div>
        </div>
        <div class="field">
            <label>New password</label>
            <div class="ui left icon input">
                <i class="lock icon"></i>
                <input type="password" name="password_one" placeholder="New password" required>
            </div>
        </div>
        <div class="field">
            <label>Confirm new password</label>
            <div class="ui left icon input">
                <i class="lock icon"></i>
                <input type="password" name="password_two" placeholder="Confirm new password" required>
            </div>
        </div>
        <br>
        {% csrf_token %}
        <button class="ui green button" type="submit">Save</button>
    </form>
</div>
{% endblock %}