teamspace/urls.py
from django.conf.urls import include
from django.conf.urls import url
from teamspace.views import frontend
from teamspace.views import dashboard
from teamspace.views import organization
from teamspace.views import team
from teamspace.views import google

handler404 = 'teamspace.views.errors.handler404'

urlpatterns = [

    # Frontend routes
    url(r'^', include([
        url(r'^$', frontend.home, name='home'),
        url(r'^about/$', frontend.about, name='about'),
        url(r'^login/$', frontend.login, name='login'),
        url(r'^logout/$', frontend.logout, name='logout'),
        url(r'^signup/$', frontend.signup, name='signup'),
    ], namespace='frontend')),

    # Dashboard routes
    url(r'^d/', include([

        # Root dashboard routes
        url(r'^$', dashboard.home, name='home'),

        # Account management routes
        url(r'^u/', include([
            url(r'^edit/$', dashboard.user_edit, name='edit'),
            url(r'^password/$', dashboard.user_password, name='password'),
        ], namespace='user')),

        # Organization access/creation routes
        url(r'^o/', include([
            url(r'^view/$', dashboard.orgs_view, name='view'),
            url(r'^create/$', dashboard.orgs_create, name='create'),
        ], namespace='organization')),

    ], namespace='dashboard')),

    # Organization routes
    url(r'^o/([0-9]+)/', include([

        # Root organization routes
        url(r'^$', organization.home, name='home'),
        url(r'^users/$', organization.users, name='users'),
        url(r'^leave/$', organization.leave, name='leave'),
        url(r'^delete/$', organization.delete, name='delete'),

        # Organization management routes
        url(r'^m/', include([
            url(r'^edit/$', organization.manage_edit, name='edit'),
            url(r'^users/$', organization.manage_users, name='users'),
        ], namespace='manage')),

        # Team access/creation routes
        url(r'^t/', include([
            url(r'^view/$', organization.teams_view, name='view'),
            url(r'^create/$', organization.teams_create, name='create'),
        ], namespace='team')),

    ], namespace='organization')),

    # Team routes
    url(r'^t/([0-9]+)/', include([

        # Root team routes
        url(r'^$', team.home, name='home'),
        url(r'^leave/$', team.leave, name='leave'),
        url(r'^delete/$', team.delete, name='delete'),
        url(r'^events/$', team.events, name='events'),
        url(r'^files/$', team.files, name='files'),
        url(r'^chat/$', team.chat, name='chat'),
        url(r'^users/$', team.users, name='users'),

        # Team management routes
        url(r'^m/', include([
            url(r'^edit/$', team.manage_edit, name='edit'),
            url(r'^users/$', team.manage_users, name='users'),
        ], namespace='manage')),

    ], namespace='team')),

    # Provider routes
    url(r'^providers/', include([

        url(r'^google/$', google.index, name='google'),

    ], namespace='providers')),

]

teamspace/models/team.py
"""
Team Model

This represents details related to a team.
"""
from django.db import models


class Team(models.Model):
    from teamspace.models import User
    from teamspace.models import Organization

    # Database fields
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    parent = models.ForeignKey(Organization, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=50000)
    members = models.IntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Define instance variables here
    def __init__(self, *args, **kwargs):
        super(Team, self).__init__(*args, **kwargs)
        self.markdown = None

teamspace/forms/organization.py
"""
Organization Forms

For more information on Forms, see
https://docs.djangoproject.com/en/1.10/topics/forms/

For more information on ModelForms, see
https://docs.djangoproject.com/en/1.10/topics/forms/modelforms/
"""
from django import forms
from teamspace.models import Organization
from teamspace.models import OrganizationMembership

FIELDS = ['name', 'description', 'address', 'country', 'state']
ERRORS = {
    'name': {
        'required': 'Please enter the name of your organization.',
        'unique': 'This organization name is taken.',
    },
    'description': {
        'required': 'Please enter an organization description.',
    },
}


class OrganizationCreateForm(forms.ModelForm):
    """
    The OrganizationCreateForm will create a new organization given the
    required fields and create an OrganizationMembership record when the form
    is saved and committed.
    """

    # Reference the Organization model
    class Meta:
        model = Organization
        fields = FIELDS
        error_messages = ERRORS

    # Define instance variables here
    def __init__(self, *args, **kwargs):
        self.owner_id = kwargs.pop('owner_id')
        super(OrganizationCreateForm, self).__init__(*args, **kwargs)

    # Specialized save function
    def save(self, commit=True):
        organization = super(OrganizationCreateForm, self).save(commit=False)
        organization.owner_id = self.owner_id
        if commit:
            organization.save()
            OrganizationMembership.objects.create(organization_id=organization.id, user_id=organization.owner_id)
        return organization


class OrganizationEditForm(forms.ModelForm):
    """
    The OrganizationEditForm will update an existing organization given an instance
    of the Organization and post data if it exists. The Organization will be saved
    when the form is saved.
    """

    # Reference the Organization model
    class Meta:
        model = Organization
        fields = FIELDS
        error_messages = ERRORS

teamspace/forms/team.py
"""
Team Forms

For more information on Forms, see
https://docs.djangoproject.com/en/1.10/topics/forms/

For more information on ModelForms, see
https://docs.djangoproject.com/en/1.10/topics/forms/modelforms/
"""
from django import forms
from teamspace.models import Team
from teamspace.models import TeamMembership

FIELDS = ['name', 'description']
ERRORS = {
    'name': {
        'required': 'Please enter your team name.',
        'unique': 'This team name is taken.',
    },
    'description': {
        'required': 'Please enter a team description.',
    },
}


class TeamCreateForm(forms.ModelForm):
    """
    The TeamCreateForm will create a new team given the required fields and
    create a TeamMembership record when the form is saved and committed.
    """

    # Reference the Team model
    class Meta:
        model = Team
        fields = FIELDS
        error_messages = ERRORS

    # Define instance variables here
    def __init__(self, *args, **kwargs):
        self.owner_id = kwargs.pop('owner_id')
        self.parent_id = kwargs.pop('parent_id')
        super(TeamCreateForm, self).__init__(*args, **kwargs)

    # Specialized save function
    def save(self, commit=True):
        team = super(TeamCreateForm, self).save(commit=False)
        team.owner_id = self.owner_id
        team.parent_id = self.parent_id
        if commit:
            team.save()
            TeamMembership.objects.create(team_id=team.id, user_id=team.owner_id)
        return team


class TeamEditForm(forms.ModelForm):
    """
    The TeamEditForm will update an existing team given an instance
    of the Team and post data if it exists. The Team will be saved
    when the form is saved.
    """

    # Reference the Team model
    class Meta:
        model = Team
        fields = FIELDS
        error_messages = ERRORS

teamspace/views/organization.py
"""
Organization Controller

For more information on controllers (views), see
https://docs.djangoproject.com/en/1.10/#the-view-layer

For the full list of requests and their responses, see
https://docs.djangoproject.com/en/1.10/ref/request-response/
"""
from django.http import Http404
from django.contrib import messages
from django.shortcuts import render
from django.shortcuts import redirect
from teamspace.utils import get_users
from teamspace.utils import format_errors
from teamspace.utils import format_description
from teamspace.models import Team
from teamspace.models import Organization
from teamspace.models import OrganizationMembership
from teamspace.forms.user import AddMember
from teamspace.forms.team import TeamCreateForm
from teamspace.forms.organization import OrganizationEditForm
from teamspace.views.decorators import require_org_owner
from teamspace.views.decorators import require_org_member
from teamspace.views.decorators import require_authenticated


@require_authenticated
@require_org_member
def leave(request, id):
    """
    Deletes the membership record of the queried organization if the user is a member.

    :param request:
    :param id: Organization ID
    :return: redirect
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()

    # Fetch the corresponding organization membership
    try:
        membership = OrganizationMembership.objects.get(user_id=request.user.id, organization_id=organization.id)
    except OrganizationMembership.DoesNotExist:
        raise Http404()

    # Delete the membership and decrement the member count
    if membership:
        membership.delete()
        organization.members -= 1
        organization.save()
        messages.info(request, 'You have left the organization.')

    # Redirect the user back to the organization view
    return redirect('dashboard:organization:view')


@require_authenticated
@require_org_owner
def delete(request, id):
    """
    Deletes the queried organization if the user is the owner.

    :param request:
    :param id: Organization ID
    :return: redirect
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()

    # Make sure the user is the owner
    if organization.owner_id == request.user.id:
        organization.delete()
        messages.info(request, 'The organization has been deleted.')

    # Redirect the user back to the organization view
    return redirect('dashboard:organization:view')


@require_authenticated
@require_org_member
def home(request, id):
    """
    Returns a view with the queried organization and a parsed markdown description.

    :param request:
    :param id: Organization ID
    :return: render
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()

    # Parse the description
    organization.markdown = format_description(organization.description)

    # Give the template a title
    title = organization.name + ': Home'

    # Render the template with the queried data set
    return render(request, 'backend/organization/home.html', {
        'title': title, 'organization': organization,
    })


@require_authenticated
@require_org_member
def users(request, id):
    """
    Returns a view containing a list of members in the queried organization.

    :param request:
    :param id: Organization ID
    :return: render
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.defer('description', 'address', 'country', 'state').get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()

    # Get a list of organization members (as users)
    users = get_users(id, 'organization')

    # Give the template a title
    title = organization.name + ': Users'

    # Render the template with the queried data set
    return render(request, 'backend/organization/users.html', {
        'title': title, 'users': users, 'organization': organization,
    })


@require_authenticated
@require_org_member
def teams_view(request, id):
    """
    Returns a view containing a list of teams in the queried organization.

    :param request:
    :param id: Organization ID
    :return: render
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.defer('description', 'address', 'country', 'state').get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()

    # TODO: If the user is the organization owner, show all the teams.
    # TODO: If they are not the owner, then only show teams where they are a member.
    # Fetch the corresponding list of teams
    teams = Team.objects.defer('description').filter(parent_id=id)

    # Flash a message if the list of teams is empty
    if not teams:
        messages.info(request, 'Your organization does not have any teams. Go create one!')

    # Give the template a title
    title = organization.name + ': View Teams'

    # Render the template with the queried data set
    return render(request, 'backend/organization/teams_view.html', {
        'title': title, 'teams': teams, 'organization': organization,
    })


@require_authenticated
@require_org_member
def teams_create(request, id):
    """
    Returns a view where users can create a team within the queried organization.

    :param request:
    :param id: Organization ID
    :return: render, redirect
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.defer('description', 'address', 'country', 'state').get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()

    # Give the template a title
    title = organization.name + ': Create Team'

    # Handle a POST method
    if request.method == 'POST':

        # Process the post data in the form
        form = TeamCreateForm(request.POST, parent_id=id, owner_id=request.user.id)

        # Check if the form is valid
        if form.is_valid():

            # Create the team
            team = form.save()

            # Post a success message
            messages.success(request, 'Team successfully created.')

            # Redirect to the newly created team
            return redirect('team:home', team.id)

        else:

            # Post an error message
            messages.error(request, format_errors(form.errors))

            # Return with the errors otherwise
            return render(request, 'backend/organization/teams_create.html', {
                'title': title, 'form': form, 'organization': organization,
            })

    # Render the template with the queried data set
    return render(request, 'backend/organization/teams_create.html', {
        'title': title, 'organization': organization,
    })


@require_authenticated
@require_org_owner
def manage_edit(request, id):
    """
    Returns a view where an owner can edit their organization.

    :param request:
    :param id: Organization ID
    :return: render
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()

    # Give the template a title
    title = organization.name + ': Edit'

    # Handle a POST method
    if request.method == 'POST':

        # Update the form with the post data
        form = OrganizationEditForm(request.POST, instance=organization)

        # Check if the form is valid
        if form.is_valid():

            # Update and save the organization
            form.save()

            # Post a success message
            messages.success(request, 'Settings successfully saved.')

        else:

            # Post an error message
            messages.error(request, format_errors(form.errors))

    else:

        # Give the default form
        form = OrganizationEditForm(instance=organization)

    # Render the template with the queried data set
    return render(request, 'backend/organization/manage_edit.html', {
        'title': title, 'form': form, 'organization': organization,
    })


@require_authenticated
@require_org_owner
def manage_users(request, id):
    """
    Returns a view with a list of users and a form to add users.

    :param request:
    :param id: Organization ID
    :return: render
    """

    # Fetch the corresponding organization
    try:
        organization = Organization.objects.defer('description', 'address', 'country', 'state').get(pk=id)
    except Organization.DoesNotExist:
        raise Http404()
    form = None

    # Handle a POST method
    if request.method == 'POST':

        # Handle invitations by creating a membership record
        if 'email' in request.POST:

            # Process the email address
            form = AddMember(request.POST, id=id, organization=True)

            # Check if the form is valid
            if form.is_valid():

                # Create the membership record
                form.add_member()
                organization.members += 1
                organization.save()

                # Post a success message
                messages.success(request, 'User successfully added.')

            else:

                # Post an error message
                messages.error(request, format_errors(form.errors))

        # Handle removals by deleting the membership record
        if 'id' in request.POST:

            # ID is non-user controlled, so assume it's safe
            remove_user_id = int(request.POST.get('id'))

            # Find and delete the membership record
            try:
                OrganizationMembership.objects.get(user_id=remove_user_id, organization_id=id).delete()
            except OrganizationMembership.DoesNotExist:

templates/backend/partials/menu.html
{% load static %}

<!-- HIDE DEFAULT SPACER -->
<a class="item" style="visibility: hidden; padding: 0;"></a>

<!-- DASHBOARD -->
<a class="item" href="{% url 'dashboard:home' %}">
    <h4 align="center">Dashboard</h4>
</a>

{% if organization %}
    <!-- ORGANIZATION MENU -->
    <div class="item">
        <b>{{ organization.name }}</b>
    </div>
    <a class="{% if request.resolver_match.view_name == 'organization:home' %}active {% endif %}item" href="{% url 'organization:home' organization.id %}">
        <small>Home</small>
    </a>
    <a class="{% if request.resolver_match.view_name == 'organization:users' %}active {% endif %}item" href="{% url 'organization:users' organization.id %}">
        <small>Users</small>
    </a>
    <a class="{% if request.resolver_match.namespace == 'organization:team' %}active {% endif %}item" href="{% url 'organization:team:view' organization.id %}">
        <small>Teams</small>
    </a>
    {% if organization.owner_id == request.user.id %}
        <a class="{% if request.resolver_match.namespace == 'organization:manage' %}active {% endif %}item" href="{% url 'organization:manage:edit' organization.id %}">
            <small>Manage</small>
        </a>
    {% endif %}
{% endif %}

{% if team %}
    <!-- TEAM MENU -->
    <div class="item">
        <b>{{ team.name }}</b>
    </div>
    <a class="{% if request.resolver_match.view_name == 'team:home' %}active {% endif %}item" href="{% url 'team:home' team.id %}">
        <small>Home</small>
    </a>
    <a class="{% if request.resolver_match.view_name == 'team:users' %}active {% endif %}item" href="{% url 'team:users' team.id %}">
        <small>Users</small>
    </a>
    <a class="{% if request.resolver_match.view_name == 'team:events' %}active {% endif %}item" href="{% url 'team:events' team.id %}">
        <small>Events</small>
    </a>
    <a class="{% if request.resolver_match.view_name == 'team:chat' %}active {% endif %}item" href="{% url 'team:chat' team.id %}">
        <small>Chat</small>
        <!--<div class="ui label">24</div>-->
    </a>
    <a class="{% if request.resolver_match.view_name == 'team:files' %}active {% endif %}item" href="{% url 'team:files' team.id %}">
        <small>Files</small>
        <!--<div class="ui label">11</div>-->
    </a>
    {% if team.owner_id == request.user.id %}
        <a class="{% if request.resolver_match.namespace == 'team:manage' %}active {% endif %}item" href="{% url 'team:manage:edit' team.id %}">
            <small>Manage</small>
        </a>
    {% endif %}
{% endif %}

<!-- LOGOUT -->
<a class="item" href="{% url 'frontend:logout' %}">
    <h4 class="ui grey header">{{ request.user.first_name }} {{ request.user.last_name }}</h4>
    <p>Log out</p>
</a>

templates/backend/partials/notifications.html
{% if messages %}
    {% for message in messages %}
    <div class="ui icon{% if message.tags %} {{ message.tags }}{% endif %} message">
        <i class="close icon"></i>
        <div class="content">
            <div class="header">
                {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                    Heads up!
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    Success!
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                    Warning!
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    Oh snap!
                {% endif %}
            </div>
            <p>{{ message|safe }}</p>
        </div>
    </div>
    {% endfor %}
{% endif %}

templates/backend/partials/team_form.html
<!-- Team from -->
<form class="ui form" style="width: 100%;" method="POST" action="{% if request.resolver_match.view_name == 'organization:team:create' %}{% url 'organization:team:create' organization.id %}{% elif request.resolver_match.view_name == 'team:manage:edit' %}{% url 'team:manage:edit' team.id %}{% endif %}">
    <h4 class="ui dividing header">Team Information</h4>
    <div class="field">
        <label>Name</label>
        <input type="text" name="name" placeholder="Name" maxlength="100" value="{% if form %}{{ form.data.name|default:form.instance.name }}{% endif %}" required>
    </div>
    <div class="field">
        <label>Description</label>
        <textarea name="description" placeholder="Description" maxlength="50000" required>{% if form %}{{ form.data.description|default:form.instance.description }}{% endif %}</textarea>
        We support <a href="https://guides.github.com/features/mastering-markdown/">Markdown</a>.
    </div>
    <br>
    {% csrf_token %}
    <button class="ui green button" type="submit">
        {% if request.resolver_match.view_name == 'organization:team:create' %}
            Create
        {% elif request.resolver_match.view_name == 'team:manage:edit' %}
            Save
        {% endif %}
    </button>
</form>